### ISSUE TITLE
文字推理正常，无法显示图片

### ISSUE THREAD

**Issue by ghtHack** [visual-openllm/visual-openllm#10]
文字推理正常，但是无法显示图片，图片已生成在image文件夹内，就是无法显示

**Comment by PeterDing** [comment]
我之前也遇到过这个问题，是 markdown 绘制图片时路径错了，漏了一个 `/`。之后我强制使用 `gradio==3.20.1` 就正常了。

**Comment by ghtHack** [comment]
确实，已修复
