### ISSUE TITLE
chatGLM体现在哪？

### ISSUE THREAD

**Issue by FrankWhh** [visual-openllm/visual-openllm#2]
conversationBot看着跟visual-chatgpt没区别，llm都是openAI的接口啊

**Comment by mymusise** [comment]
这是一个黑魔法：https://github.com/visual-openllm/visual-openllm/blob/main/visual_openllm/openai_inject.py
@PeterDing

**Comment by FrankWhh** [comment]
刚看到了，我之前尝试直接将self.llm赋值为ChatGLM（custom LLM），ChatGLM无法按照prompt指定格式回复，当时觉得指令对齐不够啥的

**Comment by mymusise** [comment]
> 刚看到了，我之前尝试直接将self.llm赋值为ChatGLM（custom LLM），ChatGLM无法按照prompt指定格式回复，当时觉得指令对齐不够啥的

对，这个要微调下才可以

**Comment by FrankWhh** [comment]
`"visual-openllm/visual-openllm-chatglm-6b-rola"` 这个微调权重没看到呢

**Comment by FrankWhh** [comment]
是直接用Stanford Alpaca的52K数据微调的吗？

**Comment by mymusise** [comment]
> `"visual-openllm/visual-openllm-chatglm-6b-rola"` 这个微调权重没看到呢。 是直接用Stanford Alpaca的52K数据微调的吗？

不是，针对visual-openllm场景弄的数据

**Comment by FrankWhh** [comment]
> `"visual-openllm/visual-openllm-chatglm-6b-rola"` 这个微调权重没看到呢。 是直接用Stanford Alpaca的52K数据微调的吗？

看到readme了哈

**Comment by FrankWhh** [comment]
> > `"visual-openllm/visual-openllm-chatglm-6b-rola"` 这个微调权重没看到呢。 是直接用Stanford Alpaca的52K数据微调的吗？
> 
> 不是，针对visual-openllm场景弄的数据

好的。感谢
