### ISSUE TITLE
自动更新了.bin文件之后，运行run.py没问题，但是输入文字就报错

### ISSUE THREAD

**Issue by hunterabc** [visual-openllm/visual-openllm#28]
部分.bin文件自动更新了之后，运行run.py没问题。
但是输入“生成一张金毛狗的图片”之后，报错“ValueError: 150001 is not in list”

![111](https://user-images.githubusercontent.com/29114723/230867910-ff751515-57ee-419a-8ac9-501f2d11291d.jpg)
![222](https://user-images.githubusercontent.com/29114723/230867937-cc074dee-1f8c-4086-bca8-e6288601718a.jpg)

**Comment by erowalker** [comment]
遇到了同样的问题

**Comment by yayeoCddy** [comment]
应该是chatGLM那边tokenizer更新的原因，在`from_pretrained` 加入`commit_hash` 即可
```
commit_hash = "fc937144cc67c5755497a99917fb0d1e6f3bbfb7"
self.model = ChatGLMForConditionalGeneration.from_pretrained("THUDM/chatglm-6b", device_map="auto", revision=commit_hash)
self.tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True, revision=commit_hash)
```

**Comment by erowalker** [comment]
![5644](https://user-images.githubusercontent.com/11721612/231098621-d09b9d57-8a3e-4e0e-9e3e-4152e0ce7a5e.jpg)
加上revision=commit_hash后会报错，后来发现把 device_map="auto",去掉就正常了。

**Comment by hunterabc** [comment]
> 应该是chatGLM那边tokenizer更新的原因，在`from_pretrained` 加入`commit_hash` 即可
> 
> ```
> commit_hash = "fc937144cc67c5755497a99917fb0d1e6f3bbfb7"
> self.model = ChatGLMForConditionalGeneration.from_pretrained("THUDM/chatglm-6b", device_map="auto", revision=commit_hash)
> self.tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True, revision=commit_hash)
> ```

感谢！我按照这个方法修改后，可以正常运行。

**Comment by g-wellsa** [comment]
what's this commit_hash mean?

**Comment by winnerahao** [comment]
方法一：按作者的方式，使用chatglm-6b在当前项目中的默认版本（具体按照上面的提示）
方法二：去chatglm-6b的github下载最新的模型文件（前提是本地运行），同时下载最新的config文件，替换掉当前项目目录下的configuration_chatglm.py与modeling_chatglm.py，这样就默认使用最新的chatglm-6b配置了。或者先不管模型用不用本地的，直接替换以上两个文件为最新的就好了

**Comment by brewswang** [comment]
替换了之后，不能实现文字转图片，怎么处理？提示如下：
非常抱歉,作为一个人工智能助手我不能为您提供画一个荷花的

**Comment by mymusise** [comment]
已更新LoRA，是因为后来chatglm模型参数更新了。
