### ISSUE TITLE
模型tokennizaer需要更新？：150001 not in list？

### ISSUE THREAD

**Issue by bigbrother666sh** [visual-openllm/visual-openllm#33]
大佬，跑下来。报错 了 150001 not in list

看了下 ChatGLM6B那边貌似更新模型，需要更新对应的tokenizer，是不是咱这边也得更新？

https://github.com/THUDM/ChatGLM-6B/issues/432

**Comment by xrunda** [comment]
+1

**Comment by mymusise** [comment]
已更新LoRA，是因为后来chatglm模型参数更新了。
