### ISSUE TITLE
 size mismatch for base_model.model.transformer.layers.0.attention.query_key_value.lora_A.default.weight: copying a param with shape torch.Size([32, 4096]) from checkpoint, the shape in current model is torch.Size([16, 4096])

### ISSUE THREAD

**Issue by frog-game** [visual-openllm/visual-openllm#36]
怎么会报这种错误呢
![image](https://github.com/visual-openllm/visual-openllm/assets/31720616/06b0efb4-5ab3-4f8e-86a2-00097182e668)

**Comment by scuhz** [comment]
bro,我也遇到了这个问题。我的原因是因为训练的时候和加载模型的时候peft包的版本不一样，训练的时候peft包的版本是0.3.0dev，加载模型的时候是0.3.0，你可以检查一下peft包的版本

**Comment by jundeli** [comment]
出现了同样的问题，怎么解决呢？

**Comment by mymusise** [comment]
已更新LoRA，是因为后来chatglm模型参数更新了。

**Comment by Godsing** [comment]
> bro,我也遇到了这个问题。我的原因是因为训练的时候和加载模型的时候peft包的版本不一样，训练的时候peft包的版本是0.3.0dev，加载模型的时候是0.3.0，你可以检查一下peft包的版本

还真是这个原因！

我遇到了完全相同的报错。

先尝试安装 0.3.0.dev0 的 commit 记录对应的版本：

```sh
pip install git+https://github.com/huggingface/peft.git@50aaf99
```

依然报错。

然后尝试安装 0.3.0.dev0 往后一小段时间的 commit 记录对应的版本：

```sh
pip install git+https://github.com/huggingface/peft.git@51f49a5
```

终于成功了！

看来 PEFT 这个包的兼容性目前是真的很差。

对于遇到相同问题的朋友，如果上面 “51f49a5” 这个 commit 版本对你来说依然不行，可以尝试用二分搜索，在一定的 commit 记录范围内逐个去试。由于不同的 commit 可能存在相同的版本号，因此在尝试不同的 commit 时，建议先卸载 peft，再安装，免得因 pip 自动判断为同一版本号而忽略更新。
