### ISSUE TITLE
 Did not find openai_api_key

### ISSUE THREAD

**Issue by ghtHack** [visual-openllm/visual-openllm#4]
ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass
`openai_api_key` as a named parameter. (type=value_error)

**Comment by Bvirgo** [comment]
# We can't just set the memory to model_size // num_devices as it will end being too   │
# slightly less layers and some layers will end up offload at the end. So this funct
ZeroDivisionError: integer division or modulo by zero
