### ISSUE TITLE
成功复刻w

### ISSUE THREAD

**Issue by MrToy** [visual-openllm/visual-openllm#6]
感谢提供的参考代码，成功复刻，https://github.com/MrToy/visual-chatgpt
其中，用LangChain的custom llm替代了inject
顺便咨询下，lora权重用的什么数据集训练的做到了识别指令。我自己训练的alpaca权重识别不了

**Comment by bigbrother666sh** [comment]
哥们牛逼
不过，为啥我用你的repo跑起来，“帮我画一个车水马龙”或者“帮我画一个小鸡炖蘑菇”
都只能得到文字回复？

**Comment by bigbrother666sh** [comment]
哦 原来lora得加载原repo的……
