### ISSUE TITLE
推理时出错：Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

### ISSUE THREAD

**Issue by ghtHack** [visual-openllm/visual-openllm#9]
运行成功，推理时出错：Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

**Comment by Leawnn** [comment]
我也是报这个错，我根据它的报错位置，在modeling_chatglm到处缝缝补补，将tensor.to(device)，起码添加了五处地方，才运行成功了.....有没有哪位大佬知道这是啥问题
这是缝补的样例
position_id=position_id.to(device=q.device)

**Comment by Leawnn** [comment]
我单卡也报这个错，一个tensors 在GPU上，一个tensors 在CPU上，不知道什么原因

**Comment by PeterDing** [comment]
我把模型强制放 cuda 上了，你们试试看。

**Comment by ghtHack** [comment]
已解决

**Comment by AILTY** [comment]
@ghtHack 咋解决的？请问
